export const data = [
	{
		id: 0,
		name: 'Stella Casey',
		active: false,
		company: 'PEARLESEX',
		country: 'China',
	},
	{
		id: 1,
		name: 'Valeria Thornton',
		active: false,
		company: 'DIGITALUS',
		country: 'Nicaragua',
	},
	{
		id: 2,
		name: 'Kirk Dean',
		active: false,
		company: 'ZAPPIX',
		country: 'Zimbabwe',
	},
	{
		id: 3,
		name: 'Jennings Hebert',
		active: true,
		company: 'MAINELAND',
		country: 'Somalia',
	},
	{
		id: 4,
		name: 'Kasey Hartman',
		active: false,
		company: 'OCTOCORE',
		country: 'Portugal',
	},
	{
		id: 5,
		name: 'Martina Dickerson',
		active: true,
		company: 'IMKAN',
		country: 'Croatia (Hrvatska)',
	},
	{
		id: 6,
		name: 'Anna Finley',
		active: false,
		company: 'FLYBOYZ',
		country: 'Pitcairn',
	},
	{
		id: 7,
		name: 'Byers Sharpe',
		active: true,
		company: 'KOFFEE',
		country: 'Canada',
	},
	{
		id: 8,
		name: 'Peggy Washington',
		active: true,
		company: 'NORSUL',
		country: 'French Southern Territories',
	},
]